export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_ARTICLES_TO_DISPLAY = 'SET_ARTICLES_TO_DISPLAY';
export const SET_MY_SAVED_ARTICLES = 'SET_MY_SAVED_ARTICLES';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';

export const SET_IS_PRELOADER_SHOW = 'SET_IS_PRELOADER_SHOW';
export const SET_IS_NOT_FOUND_SHOW = 'SET_IS_NOT_FOUND_SHOW';
export const SET_IS_ERROR_NEWS_SERVER = 'SET_IS_ERROR_NEWS_SERVER';
export const SET_IS_NEWS_CARD_LIST_SHOW = 'SET_IS_NEWS_CARD_LIST_SHOW';

export const SET_IS_LOGIN_POPUP_OPEN = 'SET_IS_LOGIN_POPUP_OPEN';
export const SET_IS_REGISTER_POPUP_OPEN = 'SET_IS_REGISTER_POPUP_OPEN';
export const SET_IS_MOBILE_HEADER_POPUP_OPEN = 'SET_IS_MOBILE_HEADER_POPUP_OPEN';
export const SET_IS_SUCCESS_POPUP_OPEN = 'SET_IS_SUCCESS_POPUP_OPEN';
