export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_ARTICLES_TO_DISPLAY = 'SET_ARTICLES_TO_DISPLAY';
export const SET_MY_SAVED_ARTICLES = 'SET_MY_SAVED_ARTICLES';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
